namespace RemoteExecution
{
    class LW10
    {
        public static string[] FileFormat =
            {
                "DeluxeRLA(.rla)",
                "LW_Alias(.als)",
                "LW_BMP24(.bmp)",
                "LW_BMP32(.bmp)",
                "CineonFP(.cin)",
                "LW_JPEG(.jpg)",
                "LW_OpenEXR_RGBAFP(.exr)",
                "LW_OpenEXR_RGBAHALF(.exr)",
                "LW_OpenEXR_RGBFP(.exr)",
                "LW_OpenEXR_RGBHALF(.exr)",
                "LW_PCX(.pcx)",
                "LW_PICT24(.pct)",
                "LW_PICT32(.pct)",
                "LW_PNG24(.png)",
                "LW_PNG32(.png)",
                "LW_PShop24(.psd)",
                "LW_PShop32(.psd)",
                "LW_RLA24(.rla)",
                "LW_RLA32(.rla)",
                "Radiance(.hdr)",
                "LW_SGI24(rgb)",
                "LW_SGI32(.rgb)",
                "SGI48-bit(rgb)",
                "SGI64-bit(.rgb)",
                "LW_SUN24(.ras)",
                "LW_SUN32(.ras)",
                "LW_TGA24(.tga)",
                "LW_TGA32(.tga)",
                "LW_TIFF24(.tif)",
                "LW_TIFF24FP(.tif)",
                "LW_TIFF32(.tif)",
                "LW_TIFF32FP(.tif)",
                "LW_YPB(.ypb)",
                "LW_YUV(.yuv)",
                "flexibleFormat(.flx)",
                "flexibleFomratLegacy(.flx)",
                "IFFILBMFormat(.iff)",
                "IFF32ILBMFormat(.iff)",
                "LW_TGA_SRC(.tga)"
            };
    }
}
