namespace RemoteExecution
{
    class LW20xx
    {
        public static string[] FileFormat =
        {
            "Deluxe RLA(.rla)",
            "LW_Alias(.als)",
            "LW_BMP24(.bmp)",
            "LW_BMP32(.bmp)",
            "Cineon FP(.cin)",
            "LW_DPX_RGB10(.dpx)",
            "LW_DPX_RGB12(.dpx)",
            "LW_DPX_RGB16(.dpx)",
            "LW_DPX_RGB8(.dpx)",
            "LW_DPX_RGBA10(.dpx)",
            "LW_DPX_RGBA12(.dpx)",
            "LW_DPX_RGBA16(.dpx)",
            "LW_DPX_RGBA8(.dpx)",
            "LW_DPX_RGBAFP(.dpx)",
            "LW_DPX_RGBFP(.dpx)",
            "LW_JPEG(.jpg)",
            "LW_OpenEXR_RGBAFP(.exr)",
            "LW_OpenEXR_RGBAHALF(.exr)",
            "LW_OpenEXR_RGBFP(.exr)",
            "LW_OpenEXR_RGBHALF(.exr)",
            "LW_PCX(.pcx)",
            "LW_PICT24(.pct)",
            "LW_PICT32(.pct)",
            "LW_PNG24(.png)",
            "LW_PNG32(.png)",
            "LW_PShop24(.psd)",
            "LW_PShop32(.psd)",
            "LW_PyBobImageSaver(.bob)",
            "LW_RLA24(.rla)",
            "LW_RLA32(.rla)",
            "LW_Radiance(.hdr)",
            "LW_SGI24(.rgb)",
            "LW_SGI32(.rgb)",
            "SGI 48-bit(.rgb)",
            "SGI 64-bit(.rgb)",
            "LW_SUN24(.ras)",
            "LW_SUN32(.ras)",
            "LW_TGA24(.tga)",
            "LW_TGA32(.tga)",
            "LW_TIFF24(.tif)",
            "LW_TIFF24FP(.tif)",
            "LW_TIFF32(.tif)",
            "LW_TIFF32FP(.tif)",
            "LW_VPB(.vpb)",
            "LW_YUV(.yuv)",
            "Flexible Format(.flx)",
            "Flexible Format Legacy(.flx)",
            "IFF ILBM Format(.iff)",
            "IFF32 ILBM Format(.iff)",
            "LW_TGA_SRC(.tga)",
        };
    }
}
